### ISSUE TITLE
图表可以 bridge iOS 和 Android 本地库,最近在项目里实现了一个，过阵子整理下open出来

### ISSUE THREAD

**Issue by buhe** [beefe/qianlong#1]
:)

**Comment by xwenliang** [comment]
:+1: 
这个项目是一开始尝试了下，后面没有再做维护，真正的项目放到私有仓库里了，然后我们把开发过程中遇到一些需要封装的组件独立了出来，啥时候open出来了发个链接过来呀 :)

**Comment by buhe** [comment]
一定的！最近在做项目也是准备用你们的wechat sdk, 互相学习!
目前自己做一个独立的项目，跟你们想的一样，也是希望把过程中的组件开放出来
